# Codemagic CI/CD Configuration for v-life
# iOS ONLY - Android is built locally and uploaded manually
# Capacitor 8 requires Node 22
# iOS uses Swift Package Manager (SPM), NOT CocoaPods

workflows:
  # ============================================
  # iOS Release Build (App Store)
  # ============================================
  ios-release:
    name: iOS App Store Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.vlife.ios
      groups:
        - ios_credentials
      vars:
        BUNDLE_ID: app.vlife.ios
        APP_NAME: v-life
        XCODE_SCHEME: App
        XCODE_PROJECT: ios/App/App.xcodeproj
      node: 22
      xcode: latest

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
      tag_patterns:
        - pattern: 'v*-ios'
          include: true

    scripts:
      - name: Install Node dependencies
        script: npm ci

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Resolve Swift Package Dependencies
        script: |
          cd ios/App
          xcodebuild -resolvePackageDependencies -project App.xcodeproj -scheme App

      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles --project "$XCODE_PROJECT"

      - name: Increment build number
        script: |
          cd ios/App
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo "0")
          NEW_BUILD=$((LATEST_BUILD + 1))
          agvtool new-version -all $NEW_BUILD
          echo "Build number set to $NEW_BUILD"

      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild \
            -project App.xcodeproj \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive \
            CODE_SIGN_STYLE=Manual

      - name: Export IPA
        script: |
          xcode-project export-ipa \
            --project "$XCODE_PROJECT" \
            --archive ios/App/build/App.xcarchive

    artifacts:
      - ios/App/build/**/*.ipa
      - ios/App/build/**/*.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  # ============================================
  # iOS TestFlight Build (develop branch)
  # ============================================
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.vlife.ios
      groups:
        - ios_credentials
      vars:
        BUNDLE_ID: app.vlife.ios
        XCODE_SCHEME: App
        XCODE_PROJECT: ios/App/App.xcodeproj
      node: 22
      xcode: latest

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true

    scripts:
      - name: Install Node dependencies
        script: npm ci

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Resolve Swift Package Dependencies
        script: |
          cd ios/App
          xcodebuild -resolvePackageDependencies -project App.xcodeproj -scheme App

      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles --project "$XCODE_PROJECT"

      - name: Increment build number
        script: |
          cd ios/App
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo "0")
          agvtool new-version -all $((LATEST_BUILD + 1))

      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild \
            -project App.xcodeproj \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive \
            CODE_SIGN_STYLE=Manual

      - name: Export IPA
        script: |
          xcode-project export-ipa \
            --project "$XCODE_PROJECT" \
            --archive ios/App/build/App.xcarchive

    artifacts:
      - ios/App/build/**/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
