# Codemagic CI/CD Configuration for v-life
# iOS ONLY - Android is built locally and uploaded manually
# Capacitor 8 requires Node 22
# iOS uses Swift Package Manager (SPM), NOT CocoaPods

workflows:
  # ============================================
  # iOS Release Build (App Store)
  # ============================================
  ios-release:
    name: iOS App Store Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: ELITE-TEAM-API-KEY
    environment:
      vars:
        BUNDLE_ID: app.vlife.ios
        APP_NAME: v-life
        XCODE_SCHEME: App
        XCODE_PROJECT: ios/App/App.xcodeproj
      node: 22
      xcode: latest

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
      tag_patterns:
        - pattern: 'v*-ios'
          include: true

    scripts:
      - name: Install Node dependencies
        script: npm ci

      - name: Build web app
        script: npm run build

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Resolve Swift Package Dependencies
        script: |
          cd ios/App
          xcodebuild -resolvePackageDependencies -project App.xcodeproj -scheme App

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles --project "$XCODE_PROJECT"

      - name: Build iOS app
        script: |
          cd ios/App
          xcode-project build-ipa \
            --project "App.xcodeproj" \
            --scheme "App"

    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - ios/App/*.ipa
      - ios/App/build/ios/xcarchive/*.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  # ============================================
  # iOS TestFlight Build (develop branch)
  # ============================================
  ios-testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: ELITE-TEAM-API-KEY
    environment:
      vars:
        BUNDLE_ID: app.vlife.ios
        XCODE_SCHEME: App
        XCODE_PROJECT: ios/App/App.xcodeproj
      node: 22
      xcode: latest

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true

    scripts:
      - name: Install Node dependencies
        script: npm ci

      - name: Build web app
        script: npm run build

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Resolve Swift Package Dependencies
        script: |
          cd ios/App
          xcodebuild -resolvePackageDependencies -project App.xcodeproj -scheme App

      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles --project "$XCODE_PROJECT"

      - name: Build iOS app
        script: |
          cd ios/App
          xcode-project build-ipa \
            --project "App.xcodeproj" \
            --scheme "App"

    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - ios/App/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
